# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test123():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_123(self):
    self.driver.get("https://tv.kyivstar.ua/ua/")
    self.driver.maximize_window()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_login").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".step-button:nth-child(2) > .btn").click()
    time.sleep(7)
    self.driver.find_element(By.CSS_SELECTOR, ".ng-valid:nth-child(2)").send_keys("demo_ro2")
    # self.driver.find_element(By.CSS_SELECTOR, ".login-input_password").send_keys("123456")
    # self.driver.find_element(By.CSS_SELECTOR, ".dark:nth-child(1) .ng-dirty").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-container").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-container").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".next-step").click()
    # element = self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-active img")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # element = self.driver.find_element(By.CSS_SELECTOR, "body")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element, 0, 0).perform()
    # self.driver.find_element(By.CSS_SELECTOR, ".profile-link > .icon-profile").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".main-content > .ng-star-inserted").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".ng-dirty:nth-child(1)").send_keys("demo_ro2")
    # self.driver.find_element(By.CSS_SELECTOR, ".main-content > .ng-star-inserted").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".dark:nth-child(3) .form__input").send_keys("demo_ro2")
    # self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
  
