# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHttpstvkyivstarua():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_httpstvkyivstarua(self):
    self.driver.get("https://tv.kyivstar.ua/ua/")
    self.driver.maximize_window()
    self.driver.find_element(By.CSS_SELECTOR, ".nav__search > .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".types > .btn:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched:nth-child(1)").send_keys("суперсила")
    self.driver.find_element(By.CSS_SELECTOR, ".search-tile:nth-child(1) > .content-img:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accent > .icon-play").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-accent > .icon-play")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".step-button:nth-child(2) > .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".step-button:nth-child(2) > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-valid:nth-child(1)").send_keys("demo_ro2")
    self.driver.find_element(By.CSS_SELECTOR, ".login-input_password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".dark:nth-child(1) .ng-dirty").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-overlay-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next-step").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
  
